"""Added roles relation

Revision ID: 00265ad0c721
Revises: ebdfe140e130
Create Date: 2023-05-05 09:10:11.035784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00265ad0c721'
down_revision = 'ebdfe140e130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_user_id_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'user_id')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('roles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('roles_user_id_fkey', 'roles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
