"""Fixing the models

Revision ID: 015584e37878
Revises: 38d020232fb7
Create Date: 2023-05-08 17:21:42.012330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015584e37878'
down_revision = '38d020232fb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('alumni_experiences_alumni_data_id_fkey', 'alumni_experiences', type_='foreignkey')
    op.create_foreign_key(None, 'alumni_experiences', 'alumni_data', ['alumni_data_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('faculty_experiences_faculty_data_id_fkey', 'faculty_experiences', type_='foreignkey')
    op.create_foreign_key(None, 'faculty_experiences', 'faculty_data', ['faculty_data_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculty_experiences', type_='foreignkey')
    op.create_foreign_key('faculty_experiences_faculty_data_id_fkey', 'faculty_experiences', 'faculty_data', ['faculty_data_id'], ['id'])
    op.drop_constraint(None, 'alumni_experiences', type_='foreignkey')
    op.create_foreign_key('alumni_experiences_alumni_data_id_fkey', 'alumni_experiences', 'alumni_data', ['alumni_data_id'], ['id'])
    # ### end Alembic commands ###
