"""Added faculty experience table

Revision ID: 0a572a55554f
Revises: 37af2629b021
Create Date: 2023-05-05 23:32:23.355391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a572a55554f'
down_revision = '37af2629b021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('faculty_data_id', sa.Integer(), nullable=True),
    sa.Column('faculty_data_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_data_id'], ['faculty_data.id'], ),
    sa.PrimaryKeyConstraint('id', 'faculty_data_user_id')
    )
    op.create_index(op.f('ix_faculty_experiences_department'), 'faculty_experiences', ['department'], unique=False)
    op.create_index(op.f('ix_faculty_experiences_id'), 'faculty_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_faculty_experiences_organization'), 'faculty_experiences', ['organization'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_experiences_organization'), table_name='faculty_experiences')
    op.drop_index(op.f('ix_faculty_experiences_id'), table_name='faculty_experiences')
    op.drop_index(op.f('ix_faculty_experiences_department'), table_name='faculty_experiences')
    op.drop_table('faculty_experiences')
    # ### end Alembic commands ###
