"""Added timestamp for questions and answers table

Revision ID: 13582e3d99c9
Revises: b1c7cb7e986c
Create Date: 2023-05-18 18:20:50.006035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13582e3d99c9'
down_revision = 'b1c7cb7e986c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'created_at')
    op.drop_column('answers', 'created_at')
    # ### end Alembic commands ###
