"""Changed some code

Revision ID: 13b80796e00a
Revises: 8dd088766d6d
Create Date: 2023-05-19 18:44:55.630921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13b80796e00a'
down_revision = '8dd088766d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
