"""Updated users table

Revision ID: 309667f0c4c1
Revises: b3661cefe4df
Create Date: 2023-05-05 10:06:49.075421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '309667f0c4c1'
down_revision = 'b3661cefe4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
