"""Changed some code

Revision ID: 3197f5065ab5
Revises: 13b80796e00a
Create Date: 2023-05-19 18:47:11.577707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3197f5065ab5'
down_revision = '13b80796e00a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
