"""Added timestamp for users table

Revision ID: 32d466382dfa
Revises: a3538bb54769
Create Date: 2023-05-18 17:48:25.578048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32d466382dfa'
down_revision = 'a3538bb54769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
