"""Fixing the models

Revision ID: 38ff02fcd77c
Revises: 015584e37878
Create Date: 2023-05-08 17:41:44.393446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ff02fcd77c'
down_revision = '015584e37878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
