"""Fixing the models

Revision ID: 3b91ec2a1296
Revises: 61993259dbe5
Create Date: 2023-05-08 17:09:31.969181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b91ec2a1296'
down_revision = '61993259dbe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
