"""Fixed the users table

Revision ID: 3dc436007aef
Revises: 43e768612a6d
Create Date: 2023-05-06 09:11:06.572443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc436007aef'
down_revision = '43e768612a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
