"""Added more models

Revision ID: 4d383a772271
Revises: 5f4a1d4c305c
Create Date: 2023-05-19 09:35:15.670430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d383a772271'
down_revision = '5f4a1d4c305c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
