"""Added more tables

Revision ID: 50560d25bdd2
Revises: d593b12b0076
Create Date: 2023-05-06 23:28:49.709993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50560d25bdd2'
down_revision = 'd593b12b0076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_alumni_data_id'), 'alumni_data', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumni_data_id'), table_name='alumni_data')
    op.drop_table('alumni_data')
    # ### end Alembic commands ###
