"""Fixing the models

Revision ID: 61993259dbe5
Revises: 6530640a2297
Create Date: 2023-05-08 17:07:07.095702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61993259dbe5'
down_revision = '6530640a2297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comments_post_id_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_post_id_fkey', 'comments', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
