"""added some constraints to hand raising model

Revision ID: 620b1d043f2d
Revises: 6bba765ebf92
Create Date: 2023-05-20 09:19:07.520966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '620b1d043f2d'
down_revision = '6bba765ebf92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hand_raises_question_id_fkey', 'hand_raises', type_='foreignkey')
    op.create_foreign_key(None, 'hand_raises', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hand_raises', type_='foreignkey')
    op.create_foreign_key('hand_raises_question_id_fkey', 'hand_raises', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###
