"""created announcements table

Revision ID: 6880ccde2eec
Revises: 13582e3d99c9
Create Date: 2023-05-18 18:36:07.823343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6880ccde2eec'
down_revision = '13582e3d99c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
