"""Added something

Revision ID: 71050f5f17ab
Revises: 
Create Date: 2023-06-15 23:58:54.694379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71050f5f17ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_profile_created', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_profile_created')
    # ### end Alembic commands ###
