"""Added student_data table

Revision ID: 7fa23328b85b
Revises: 309667f0c4c1
Create Date: 2023-05-05 19:27:10.978616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa23328b85b'
down_revision = '309667f0c4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('semester', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_data_branch'), 'student_data', ['branch'], unique=False)
    op.create_index(op.f('ix_student_data_department'), 'student_data', ['department'], unique=False)
    op.create_index(op.f('ix_student_data_semester'), 'student_data', ['semester'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_data_semester'), table_name='student_data')
    op.drop_index(op.f('ix_student_data_department'), table_name='student_data')
    op.drop_index(op.f('ix_student_data_branch'), table_name='student_data')
    op.drop_table('student_data')
    # ### end Alembic commands ###
