"""Added roles

Revision ID: 8a8f0842b0de
Revises: b96cc9b9f7a5
Create Date: 2023-05-05 08:59:50.546298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8f0842b0de'
down_revision = 'b96cc9b9f7a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
