"""Changed some code

Revision ID: 8dd088766d6d
Revises: af18219905cf
Create Date: 2023-05-19 18:43:19.721633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd088766d6d'
down_revision = 'af18219905cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
