"""Added more models

Revision ID: 8e2a37d645a6
Revises: e23432ecb975
Create Date: 2023-05-19 09:36:05.002217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2a37d645a6'
down_revision = 'e23432ecb975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
