"""Added timestamp for users table

Revision ID: 922ca6a25586
Revises: 32d466382dfa
Create Date: 2023-05-18 17:50:30.792731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922ca6a25586'
down_revision = '32d466382dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
