"""Changed some code

Revision ID: 9822d543c1c6
Revises: 8e2a37d645a6
Create Date: 2023-05-19 18:37:04.188324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9822d543c1c6'
down_revision = '8e2a37d645a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
