"""Changed some code

Revision ID: 9a21a91a6896
Revises: 3197f5065ab5
Create Date: 2023-05-19 18:49:11.723996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a21a91a6896'
down_revision = '3197f5065ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
