"""Added more tables

Revision ID: a0bf4f51575d
Revises: 50560d25bdd2
Create Date: 2023-05-06 23:30:11.119197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0bf4f51575d'
down_revision = '50560d25bdd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('alumni_data_id', sa.Integer(), nullable=False),
    sa.Column('alumni_data_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_data_id'], ['alumni_data.id'], ),
    sa.ForeignKeyConstraint(['alumni_data_user_id'], ['alumni_data.user_id'], ),
    sa.PrimaryKeyConstraint('id', 'alumni_data_id', 'alumni_data_user_id')
    )
    op.create_index(op.f('ix_alumni_experiences_id'), 'alumni_experiences', ['id'], unique=False)
    op.create_table('faculty_experiences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('faculty_data_id', sa.Integer(), nullable=False),
    sa.Column('faculty_data_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_data_id'], ['faculty_data.id'], ),
    sa.ForeignKeyConstraint(['faculty_data_user_id'], ['faculty_data.user_id'], ),
    sa.PrimaryKeyConstraint('id', 'faculty_data_id', 'faculty_data_user_id')
    )
    op.create_index(op.f('ix_faculty_experiences_id'), 'faculty_experiences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_experiences_id'), table_name='faculty_experiences')
    op.drop_table('faculty_experiences')
    op.drop_index(op.f('ix_alumni_experiences_id'), table_name='alumni_experiences')
    op.drop_table('alumni_experiences')
    # ### end Alembic commands ###
