"""Added roll_no field in users table

Revision ID: a318ae410ee7
Revises: 18daa4ddf6b1
Create Date: 2023-05-05 09:45:36.410532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a318ae410ee7'
down_revision = '18daa4ddf6b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
