"""Changed some code

Revision ID: af18219905cf
Revises: 9822d543c1c6
Create Date: 2023-05-19 18:39:03.892819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af18219905cf'
down_revision = '9822d543c1c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
