"""Updated users table

Revision ID: b3661cefe4df
Revises: 30ca9de7f6af
Create Date: 2023-05-05 10:03:05.247966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3661cefe4df'
down_revision = '30ca9de7f6af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
