"""Added more tables

Revision ID: cf037f6d6d05
Revises: a352618d7275
Create Date: 2023-05-06 23:40:41.772744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf037f6d6d05'
down_revision = 'a352618d7275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
