"""Added more tables

Revision ID: d593b12b0076
Revises: 
Create Date: 2023-05-06 23:28:37.196749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd593b12b0076'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_alumni_data_id'), 'alumni_data', ['id'], unique=True)
    op.drop_index('ix_faculty_data_designation', table_name='faculty_data')
    op.create_index(op.f('ix_faculty_data_id'), 'faculty_data', ['id'], unique=True)
    op.create_unique_constraint(None, 'faculty_data', ['user_id'])
    op.drop_index('ix_student_data_branch', table_name='student_data')
    op.drop_index('ix_student_data_department', table_name='student_data')
    op.drop_index('ix_student_data_semester', table_name='student_data')
    op.create_index(op.f('ix_student_data_id'), 'student_data', ['id'], unique=False)
    op.create_unique_constraint(None, 'student_data', ['user_id'])
    op.drop_index('ix_users_roll_no', table_name='users')
    op.create_index(op.f('ix_users_roll_no'), 'users', ['roll_no'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_roll_no'), table_name='users')
    op.create_index('ix_users_roll_no', 'users', ['roll_no'], unique=False)
    op.drop_constraint(None, 'student_data', type_='unique')
    op.drop_index(op.f('ix_student_data_id'), table_name='student_data')
    op.create_index('ix_student_data_semester', 'student_data', ['semester'], unique=False)
    op.create_index('ix_student_data_department', 'student_data', ['department'], unique=False)
    op.create_index('ix_student_data_branch', 'student_data', ['branch'], unique=False)
    op.drop_constraint(None, 'faculty_data', type_='unique')
    op.drop_index(op.f('ix_faculty_data_id'), table_name='faculty_data')
    op.create_index('ix_faculty_data_designation', 'faculty_data', ['designation'], unique=False)
    op.drop_index(op.f('ix_alumni_data_id'), table_name='alumni_data')
    op.drop_table('alumni_data')
    # ### end Alembic commands ###
