"""Added relationships for upvote and downvote

Revision ID: ee22be4a7252
Revises: 13fbf1859d2e
Create Date: 2023-05-20 10:05:08.523042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee22be4a7252'
down_revision = '13fbf1859d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
