"""Added more models

Revision ID: f6834e708609
Revises: 7fa23328b85b
Create Date: 2023-05-05 23:12:35.831055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6834e708609'
down_revision = '7fa23328b85b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
