"""Added alumni experience table

Revision ID: f9b16e522c91
Revises: 0a572a55554f
Create Date: 2023-05-05 23:37:45.387590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b16e522c91'
down_revision = '0a572a55554f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumni_experiences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('organization', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('alumni_data_id', sa.Integer(), nullable=True),
    sa.Column('alumni_data_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alumni_data_id'], ['alumni_data.id'], ),
    sa.PrimaryKeyConstraint('id', 'alumni_data_user_id')
    )
    op.create_index(op.f('ix_alumni_experiences_department'), 'alumni_experiences', ['department'], unique=False)
    op.create_index(op.f('ix_alumni_experiences_id'), 'alumni_experiences', ['id'], unique=False)
    op.create_index(op.f('ix_alumni_experiences_organization'), 'alumni_experiences', ['organization'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alumni_experiences_organization'), table_name='alumni_experiences')
    op.drop_index(op.f('ix_alumni_experiences_id'), table_name='alumni_experiences')
    op.drop_index(op.f('ix_alumni_experiences_department'), table_name='alumni_experiences')
    op.drop_table('alumni_experiences')
    # ### end Alembic commands ###
